site_name: Super Mario Bros
repo_url: https://github.com/SBD1/2024.2-Super-Mario-Bros
repo_name: SBD1/2024.2-Super-Mario-Bros

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Início: index.md
  - Entrega 1:
      - Modelo Entidade Relacionamento: entidade-relacionamento.md
      - Modelo Relacional: modelo-relacional.md
      - Dicionário: dicionario.md
      - Apresentação: apresentacao.md
  - Entrega 2:
      - DDL: ddl.md
      - DML: dml.md
      - DQL: dql.md
      - Álgebra Relacional: algebra-relacional.md
      - Apresentação: apresentacao2.md
  - Entrega 3:
      - Triggers e Stored Procedures: triggers.md

theme:
  name: material
  language: pt-BR
  logo: https://upload.wikimedia.org/wikipedia/commons/0/05/Mario_Series_Logo.svg
  features:
    - navigation.instant
    - navigation.sections 
    - navigation.top
    - navigation.tabs
    - search.suggest
    - search.highlight
    - navigation.footer
  palette:
    - scheme: default
      primary: red
      toggle:
        icon: material/weather-night
        name: Modo noturno
    - scheme: slate
      primary: red 
      toggle:
        icon: material/weather-sunny
        name: Modo claro
  icon:
    repo: fontawesome/brands/git-alt 

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Requisitos-de-Software/2024.2-Grupo07

plugins:
  - search
